name: Packer Validation

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Packer
        uses: hashicorp/setup-packer@v2
        with:
          version: latest

      - name: Initialize Packer
        run: |
          packer init packer/machine-image.pkr.hcl

      - name: Format Packer Configuration
        run: |
          packer fmt packer/machine-image.pkr.hcl

      - name: Validate Packer Configuration
        run: |
          if [ ! -f "webapp.zip" ]; then echo "Error: webapp.zip does not exist!"; exit 1; fi
          packer validate packer/machine-image.pkr.hcl

      